### ISSUE TITLE
Discuss further details with FoF authors

### ISSUE THREAD

**Issue by Erkks** [Erkks/danki-vr#4]
Speak with Lidy and Joe about their learnings from creating the physical exhibition and use the info to guide implementation

**Comment by erkkipupil** [comment]
Lidy and Joe visited Dan and I and we got some info about how to proceed:

### Get the VR representation to mimic the physical exhibit
- Get the colour hex values and timing values from Lidy
- Figure out cameras and lights and surfaces to use - do we project colour from lights or colour the objects or cameras?
- Get soundscape to use from Joe and figure out speaker configurations
- Get it ported to an immersive VR platform (not Google Cardboard)

### Exhibit the VR version of Fields of Frequencies, ideally alongside the real exhibit
- TBD

**Comment by Erkks** [comment]
Lidy and Joe visited Dan and I and we got some info about how to proceed:

### Get the VR representation to mimic the physical exhibit
- Get the colour hex values and timing values from Lidy
- Figure out cameras and lights and surfaces to use - do we project colour from lights or colour the objects or cameras?
- Get soundscape to use from Joe and figure out speaker configurations
- Get it ported to an immersive VR platform (not Google Cardboard)

### Exhibit the VR version of Fields of Frequencies, ideally alongside the real exhibit
- TBD
